# Generated by Django 5.0.6 on 2024-07-08 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fec_nac', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Producto', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=50)),
                ('precio', models.FloatField(max_length=15)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('cantidad', models.IntegerField()),
                ('categoria', models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='verdevida.categoria')),
            ],
        ),
    ]
